### ISSUE TITLE
Splash View 구현

### ISSUE THREAD

**Issue by tokirin** [TooShy/HufsTalk_Client#1]
요구사항: 어플리케이션 실행시 2초간 띄워주는 로고 View 구현
2초후에 Topic Selection View로 이동

**Comment by rrrqqq12** [comment]
로고 View 구현완료 ( 확정 이미지는 아님 )

**Comment by tokirin** [comment]
승현이 브랜치에 커밋이 없는데? 확인하고 이슈에 개발사항 공유해주세요
