### ISSUE TITLE
[개발]왼쪽 Navigation Drawer Menu 커스터마이징

### ISSUE THREAD

**Issue by tokirin** [TooShy/HufsTalk_Client#3]
우리 제품에 맞게 커스터마이징하기(Be Simple)

**Comment by rrrqqq12** [comment]
Drawer Menu에 어떤기능을 넣어야할지 잘 모르겠습니다.

**Comment by tokirin** [comment]
민석이랑 영태랑 상의해서 결정하도록. 일단 지금 기본 형태에서 바꾸는 법은 알아야겠죠?

**Comment by rrrqqq12** [comment]
넵 기본 형태에서 어떻게 바꿀지 생각해보겠습니다.!

**Comment by tokirin** [comment]
네비게이션 메뉴 잠정 삭제
