### ISSUE TITLE
Topic 선택 방법 변경 아이디어

### ISSUE THREAD

**Issue by rrrqqq12** [TooShy/HufsTalk_Client#9]
선생님, 주제선택 부분에서 저희가 생각해보았는데
임의의 주제를 리스트형식으로 나열한 후 
사용자의 선택에 따라 우선순위를 측정하여 실시간검색어처럼 
리스트순위가 바뀌도록 하는 것이 어떨지 생각해 보았습니다.

**Comment by tokirin** [comment]
서버 API 개발 완료. 클라이언트 개발 필요
